lib/pleroma/web/router.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Router do
  use Pleroma.Web, :router
  import Phoenix.LiveDashboard.Router

  pipeline :accepts_html do
    plug(:accepts, ["html"])
  end

  pipeline :accepts_html_xml do
    plug(:accepts, ["html", "xml", "rss", "atom"])
  end

  pipeline :accepts_html_json do
    plug(:accepts, ["html", "activity+json", "json"])
  end

  pipeline :accepts_html_xml_json do
    plug(:accepts, ["html", "xml", "rss", "atom", "activity+json", "json"])
  end

  pipeline :accepts_xml_rss_atom do
    plug(:accepts, ["xml", "rss", "atom"])
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
  end

  pipeline :oauth do
    plug(:fetch_session)
    plug(Pleroma.Web.Plugs.OAuthPlug)
    plug(Pleroma.Web.Plugs.UserEnabledPlug)
    plug(Pleroma.Web.Plugs.EnsureUserTokenAssignsPlug)
  end

  # Note: expects _user_ authentication (user-unbound app-bound tokens don't qualify)
  pipeline :expect_user_authentication do
    plug(Pleroma.Web.Plugs.ExpectAuthenticatedCheckPlug)
  end

  # Note: expects public instance or _user_ authentication (user-unbound tokens don't qualify)
  pipeline :expect_public_instance_or_user_authentication do
    plug(Pleroma.Web.Plugs.ExpectPublicOrAuthenticatedCheckPlug)
  end

  pipeline :authenticate do
    plug(Pleroma.Web.Plugs.OAuthPlug)
    plug(Pleroma.Web.Plugs.BasicAuthDecoderPlug)
    plug(Pleroma.Web.Plugs.UserFetcherPlug)
    plug(Pleroma.Web.Plugs.AuthenticationPlug)
  end

  pipeline :after_auth do
    plug(Pleroma.Web.Plugs.UserEnabledPlug)
    plug(Pleroma.Web.Plugs.SetUserSessionIdPlug)
    plug(Pleroma.Web.Plugs.EnsureUserTokenAssignsPlug)
    plug(Pleroma.Web.Plugs.UserTrackingPlug)
  end

  pipeline :base_api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:authenticate)
    plug(OpenApiSpex.Plug.PutApiSpec, module: Pleroma.Web.ApiSpec)
  end

  pipeline :no_auth_or_privacy_expectations_api do
    plug(:base_api)
    plug(:after_auth)
    plug(Pleroma.Web.Plugs.IdempotencyPlug)
  end

  # Pipeline for app-related endpoints (no user auth checks — app-bound tokens must be supported)
  pipeline :app_api do
    plug(:no_auth_or_privacy_expectations_api)
  end

  pipeline :api do
    plug(:expect_public_instance_or_user_authentication)
    plug(:no_auth_or_privacy_expectations_api)
  end

  pipeline :authenticated_api do
    plug(:expect_user_authentication)
    plug(:no_auth_or_privacy_expectations_api)
    plug(Pleroma.Web.Plugs.EnsureAuthenticatedPlug)
  end

  pipeline :admin_api do
    plug(:expect_user_authentication)
    plug(:base_api)
    plug(Pleroma.Web.Plugs.AdminSecretAuthenticationPlug)
    plug(:after_auth)
    plug(Pleroma.Web.Plugs.EnsureAuthenticatedPlug)
    plug(Pleroma.Web.Plugs.UserIsStaffPlug)
    plug(Pleroma.Web.Plugs.IdempotencyPlug)
  end

  pipeline :require_privileged_staff do
    plug(Pleroma.Web.Plugs.EnsureStaffPrivilegedPlug)
  end

  pipeline :require_admin do
    plug(Pleroma.Web.Plugs.UserIsAdminPlug)
  end

  pipeline :pleroma_html do
    plug(:browser)
    plug(:authenticate)
    plug(Pleroma.Web.Plugs.EnsureUserTokenAssignsPlug)
  end

  pipeline :well_known do
    plug(:accepts, ["json", "jrd+json", "xml", "xrd+xml"])
  end

  pipeline :config do
    plug(:accepts, ["json", "xml"])
    plug(OpenApiSpex.Plug.PutApiSpec, module: Pleroma.Web.ApiSpec)
  end

  pipeline :pleroma_api do
    plug(:accepts, ["html", "json"])
    plug(OpenApiSpex.Plug.PutApiSpec, module: Pleroma.Web.ApiSpec)
  end

  pipeline :mailbox_preview do
    plug(:accepts, ["html"])

    plug(:put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' 'unsafe-eval'"
    })
  end

  pipeline :http_signature do
    plug(Pleroma.Web.Plugs.HTTPSignaturePlug)
    plug(Pleroma.Web.Plugs.MappedSignatureToIdentityPlug)
  end

  pipeline :static_fe do
    plug(Pleroma.Web.Plugs.StaticFEPlug)
  end

  scope "/api/v1/pleroma", Pleroma.Web.TwitterAPI do
    pipe_through(:pleroma_api)

    get("/password_reset/:token", PasswordController, :reset, as: :reset_password)
    post("/password_reset", PasswordController, :do_reset, as: :reset_password)
    get("/emoji", UtilController, :emoji)
    get("/captcha", UtilController, :captcha)
    get("/healthcheck", UtilController, :healthcheck)
    post("/remote_interaction", UtilController, :remote_interaction)
  end

  scope "/api/v1/pleroma", Pleroma.Web do
    pipe_through(:pleroma_api)
    post("/uploader_callback/:upload_path", UploaderController, :callback)
  end

  # AdminAPI: only admins can perform these actions
  scope "/api/v1/pleroma/admin", Pleroma.Web.AdminAPI do
    pipe_through([:admin_api, :require_admin])

    put("/users/disable_mfa", AdminAPIController, :disable_mfa)

    get("/users/:nickname/permission_group", AdminAPIController, :right_get)
    get("/users/:nickname/permission_group/:permission_group", AdminAPIController, :right_get)

    post("/users/:nickname/permission_group/:permission_group", AdminAPIController, :right_add)

    delete(
      "/users/:nickname/permission_group/:permission_group",
      AdminAPIController,
      :right_delete
    )

    post("/users/permission_group/:permission_group", AdminAPIController, :right_add_multiple)

    delete(
      "/users/permission_group/:permission_group",
      AdminAPIController,
      :right_delete_multiple
    )

    post("/users/follow", UserController, :follow)
    post("/users/unfollow", UserController, :unfollow)
    post("/users", UserController, :create)

    patch("/users/suggest", UserController, :suggest)
    patch("/users/unsuggest", UserController, :unsuggest)

    get("/relay", RelayController, :index)
    post("/relay", RelayController, :follow)
    delete("/relay", RelayController, :unfollow)

    patch("/users/force_password_reset", AdminAPIController, :force_password_reset)
    get("/users/:nickname/credentials", AdminAPIController, :show_user_credentials)
    patch("/users/:nickname/credentials", AdminAPIController, :update_user_credentials)

    get("/instance_document/:name", InstanceDocumentController, :show)
    patch("/instance_document/:name", InstanceDocumentController, :update)
    delete("/instance_document/:name", InstanceDocumentController, :delete)

    patch("/users/confirm_email", AdminAPIController, :confirm_email)
    patch("/users/resend_confirmation_email", AdminAPIController, :resend_confirmation_email)

    get("/config", ConfigController, :show)
    post("/config", ConfigController, :update)
    get("/config/descriptions", ConfigController, :descriptions)
    get("/need_reboot", AdminAPIController, :need_reboot)
    get("/restart", AdminAPIController, :restart)

    get("/oauth_app", OAuthAppController, :index)
    post("/oauth_app", OAuthAppController, :create)
    patch("/oauth_app/:id", OAuthAppController, :update)
    delete("/oauth_app/:id", OAuthAppController, :delete)

    get("/media_proxy_caches", MediaProxyCacheController, :index)
    post("/media_proxy_caches/delete", MediaProxyCacheController, :delete)
    post("/media_proxy_caches/purge", MediaProxyCacheController, :purge)

    get("/frontends", FrontendController, :index)
    post("/frontends/install", FrontendController, :install)

    post("/backups", AdminAPIController, :create_backup)

    get("/email_list/subscribers.csv", EmailListController, :subscribers)
    get("/email_list/unsubscribers.csv", EmailListController, :unsubscribers)
    get("/email_list/combined.csv", EmailListController, :combined)

    get("/rules", RuleController, :index)
    post("/rules", RuleController, :create)
    patch("/rules/:id", RuleController, :update)
    delete("/rules/:id", RuleController, :delete)
  end

  # AdminAPI: admins and mods (staff) can perform these actions (if enabled by config)
  scope "/api/v1/pleroma/admin", Pleroma.Web.AdminAPI do
    pipe_through([:admin_api, :require_privileged_staff])

    delete("/users", UserController, :delete)

    get("/users/:nickname/password_reset", AdminAPIController, :get_password_reset)
    patch("/users/:nickname/credentials", AdminAPIController, :update_user_credentials)

    get("/users/:nickname/statuses", AdminAPIController, :list_user_statuses)
    get("/users/:nickname/chats", AdminAPIController, :list_user_chats)

    get("/statuses", StatusController, :index)

    get("/chats/:id", ChatController, :show)
    get("/chats/:id/messages", ChatController, :messages)
  end

  # AdminAPI: admins and mods (staff) can perform these actions
  scope "/api/v1/pleroma/admin", Pleroma.Web.AdminAPI do
    pipe_through(:admin_api)

    put("/users/tag", AdminAPIController, :tag_users)
    delete("/users/tag", AdminAPIController, :untag_users)

    patch("/users/:nickname/toggle_activation", UserController, :toggle_activation)
    patch("/users/activate", UserController, :activate)
    patch("/users/deactivate", UserController, :deactivate)
    patch("/users/approve", UserController, :approve)

    post("/users/invite_token", InviteController, :create)
    get("/users/invites", InviteController, :index)
    post("/users/revoke_invite", InviteController, :revoke)
    post("/users/email_invite", InviteController, :email)

    get("/users", UserController, :index)
    get("/users/:nickname", UserController, :show)

    get("/instances/:instance/statuses", InstanceController, :list_statuses)
    delete("/instances/:instance", InstanceController, :delete)

    get("/reports", ReportController, :index)
    get("/reports/:id", ReportController, :show)
    patch("/reports", ReportController, :update)
    post("/reports/:id/notes", ReportController, :notes_create)
    delete("/reports/:report_id/notes/:id", ReportController, :notes_delete)

    get("/statuses/:id", StatusController, :show)

lib/pleroma/web/o_auth/fallback_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.FallbackController do
  use Pleroma.Web, :controller
  alias Pleroma.Web.OAuth.OAuthController

  def call(conn, {:register, :generic_error}) do
    conn
    |> put_status(:internal_server_error)
    |> put_flash(
      :error,
      dgettext("errors", "Unknown error, please check the details and try again.")
    )
    |> OAuthController.registration_details(conn.params)
  end

  def call(conn, {:register, _error}) do
    conn
    |> put_status(:unauthorized)
    |> put_flash(:error, dgettext("errors", "Invalid Username/Password"))
    |> OAuthController.registration_details(conn.params)
  end

  def call(conn, _error) do
    conn
    |> put_status(:unauthorized)
    |> put_flash(:error, dgettext("errors", "Invalid Username/Password"))
    |> OAuthController.authorize(conn.params)
  end
end

lib/pleroma/web/o_auth/mfa_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.MFAController do
  @moduledoc """
  The model represents api to use Multi Factor authentications.
  """

  use Pleroma.Web, :controller

  alias Pleroma.MFA
  alias Pleroma.Web.Auth.TOTPAuthenticator
  alias Pleroma.Web.OAuth.MFAView, as: View
  alias Pleroma.Web.OAuth.OAuthController
  alias Pleroma.Web.OAuth.Token

  plug(:fetch_session when action in [:show, :verify])
  plug(:fetch_flash when action in [:show, :verify])

  @doc """
  Display form to input mfa code or recovery code.
  """
  def show(conn, %{"mfa_token" => mfa_token} = params) do
    template = Map.get(params, "challenge_type", "totp")

    conn
    |> put_view(View)
    |> render("#{template}.html", %{
      mfa_token: mfa_token,
      redirect_uri: params["redirect_uri"],
      state: params["state"]
    })
  end

  @doc """
  Verification code and continue authorization.
  """
  def verify(conn, %{"mfa" => %{"mfa_token" => mfa_token} = mfa_params} = _) do
    with {:ok, %{user: user, authorization: auth}} <- MFA.Token.validate(mfa_token),
         {:ok, _} <- validates_challenge(user, mfa_params) do
      conn
      |> OAuthController.after_create_authorization(auth, %{
        "authorization" => %{
          "redirect_uri" => mfa_params["redirect_uri"],
          "state" => mfa_params["state"]
        }
      })
    else
      _ ->
        conn
        |> put_flash(:error, "Two-factor authentication failed.")
        |> put_status(:unauthorized)
        |> show(mfa_params)
    end
  end

  @doc """
  Verification second step of MFA (or recovery) and returns access token.

  ## Endpoint
  POST /oauth/mfa/challenge

  params:
  `client_id`
  `client_secret`
  `mfa_token` - access token to check second step of mfa
  `challenge_type` - 'totp' or 'recovery'
  `code`

  """
  def challenge(conn, %{"mfa_token" => mfa_token} = params) do
    with {:ok, app} <- Token.Utils.fetch_app(conn),
         {:ok, %{user: user, authorization: auth}} <- MFA.Token.validate(mfa_token),
         {:ok, _} <- validates_challenge(user, params),
         {:ok, token} <- Token.exchange_token(app, auth) do
      OAuthController.after_token_exchange(conn, %{user: user, token: token})
    else
      _error ->
        conn
        |> put_status(400)
        |> json(%{error: "Invalid code"})
    end
  end

  # Verify TOTP Code
  defp validates_challenge(user, %{"challenge_type" => "totp", "code" => code} = _) do
    TOTPAuthenticator.verify(code, user)
  end

  # Verify Recovery Code
  defp validates_challenge(user, %{"challenge_type" => "recovery", "code" => code} = _) do
    TOTPAuthenticator.verify_recovery_code(user, code)
  end

  defp validates_challenge(_, _), do: {:error, :unsupported_challenge_type}
end

lib/pleroma/web/o_auth/mfa_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.MFAView do
  use Pleroma.Web, :view
  import Phoenix.HTML.Form
  alias Pleroma.MFA

  def render("mfa_response.json", %{token: token, user: user}) do
    %{
      error: "mfa_required",
      mfa_token: token.token,
      supported_challenge_types: MFA.supported_methods(user)
    }
  end
end

lib/pleroma/web/o_auth/o_auth_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.OAuthView do
  use Pleroma.Web, :view
  import Phoenix.HTML.Form

  alias Pleroma.Web.OAuth.Token.Utils

  def render("token.json", %{token: token} = opts) do
    response = %{
      id: token.id,
      token_type: "Bearer",
      access_token: token.token,
      refresh_token: token.refresh_token,
      expires_in: NaiveDateTime.diff(token.valid_until, NaiveDateTime.utc_now()),
      scope: Enum.join(token.scopes, " "),
      created_at: Utils.format_created_at(token)
    }

    if user = opts[:user] do
      response
      |> Map.put(:me, user.ap_id)
    else
      response
    end
  end
end

lib/pleroma/web/templates/o_auth/o_auth/_scopes.html.eex
<div class="scopes-input">
  <%= label @form, :scope, "The following permissions will be granted" %>
  <div class="scopes">
    <%= for scope <- @available_scopes do %>
      <%# Note: using hidden input with `unchecked_value` in order to distinguish user's empty selection from `scope` param being omitted %>
      <%= if scope in @scopes do %>
        <div class="scope">
          <%= checkbox @form, :"scope_#{scope}", value: scope in @scopes && scope, checked_value: scope, unchecked_value: "", name: "authorization[scope][]" %>
          <%= label @form, :"scope_#{scope}", String.capitalize(scope) %>
          <%= if scope in @scopes && scope do %>
            <%= String.capitalize(scope) %>
          <% end %>
        </div>
      <% else %>
        <%= checkbox @form, :"scope_#{scope}", value: scope in @scopes && scope, checked_value: scope, unchecked_value: "", name: "authorization[scope][]" %>
      <% end %>
    <% end %>
  </div>
</div>

lib/pleroma/web/templates/o_auth/o_auth/consumer.html.eex
<h2>Sign in with external provider</h2>

<%= form_for @conn, Routes.o_auth_path(@conn, :prepare_request), [as: "authorization", method: "get"], fn f -> %>
  <div style="display: none">
    <%= render @view_module, "_scopes.html", Map.merge(assigns, %{form: f}) %>
  </div>

  <%= hidden_input f, :client_id, value: @client_id %>
  <%= hidden_input f, :redirect_uri, value: @redirect_uri %>
  <%= hidden_input f, :state, value: @state %>

    <%= for strategy <- Pleroma.Config.oauth_consumer_strategies() do %>
      <%= submit "Sign in with #{String.capitalize(strategy)}", name: "provider", value: strategy %>
    <% end %>
<% end %>

lib/pleroma/web/templates/o_auth/o_auth/oob_authorization_created.html.eex
<h1>Successfully authorized</h1>
<h2>Token code is <br><%= @auth.token %></h2>

lib/pleroma/web/templates/o_auth/o_auth/oob_token_exists.html.eex
<h1>Authorization exists</h1>
<h2>Access token is <br><%= @token.token %></h2>

lib/pleroma/web/templates/o_auth/o_auth/register.html.eex
<%= if get_flash(@conn, :info) do %>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>

<h2>Registration Details</h2>

<p>If you'd like to register a new account, please provide the details below.</p>
<%= form_for @conn, Routes.o_auth_path(@conn, :register), [as: "authorization"], fn f -> %>

<div class="input">
  <%= label f, :nickname, "Nickname" %>
  <%= text_input f, :nickname, value: @nickname, autocomplete: "username" %>
</div>
<div class="input">
  <%= label f, :email, "Email" %>
  <%= text_input f, :email, value: @email, autocomplete: "email" %>
</div>

<%= submit "Proceed as new user", name: "op", value: "register" %>

<p>Alternatively, sign in to connect to existing account.</p>

<div class="input">
  <%= label f, :name, "Name or email" %>
  <%= text_input f, :name, autocomplete: "username" %>
</div>
<div class="input">
  <%= label f, :password, "Password" %>
  <%= password_input f, :password, autocomplete: "password" %>
</div>

<%= submit "Proceed as existing user", name: "op", value: "connect" %>

<%= hidden_input f, :client_id, value: @client_id %>
<%= hidden_input f, :redirect_uri, value: @redirect_uri %>
<%= hidden_input f, :scope, value: Enum.join(@scopes, " ") %>
<%= hidden_input f, :state, value: @state %>

<% end %>

lib/pleroma/web/templates/o_auth/o_auth/show.html.eex
<%= if get_flash(@conn, :info) do %>
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>

<%= form_for @conn, Routes.o_auth_path(@conn, :authorize), [as: "authorization"], fn f -> %>

<%= if @user do %>
  <div class="account-header">
    <div class="account-header__banner" style="background-image: url('<%= Pleroma.User.banner_url(@user) %>')"></div>
    <div class="account-header__avatar" style="background-image: url('<%= Pleroma.User.avatar_url(@user) %>')"></div>
    <div class="account-header__meta">
      <div class="account-header__display-name"><%= @user.name %></div>
      <div class="account-header__nickname">@<%= @user.nickname %>@<%= Pleroma.User.get_host(@user) %></div>
    </div>
  </div>
<% end %>

<div class="container__content">
  <%= if @app do %>
    <p>Application <strong><%= @app.client_name %></strong> is requesting access to your account.</p>
    <%= render @view_module, "_scopes.html", Map.merge(assigns, %{form: f}) %>
  <% end %>

  <%= if @user do %>
    <div class="actions">
      <a class="button button--cancel" href="/">Cancel</a>
      <%= submit "Approve", class: "button--approve" %>
    </div>
  <% else %>
    <%= if @params["registration"] in ["true", true] do %>
      <h3>This is the first time you visit! Please enter your Pleroma handle.</h3>
      <p>Choose carefully! You won't be able to change this later. You will be able to change your display name, though.</p>
      <div class="input">
        <%= label f, :nickname, "Pleroma Handle" %>
        <%= text_input f, :nickname, placeholder: "lain", autocomplete: "username" %>
      </div>
      <%= hidden_input f, :name, value: @params["name"] %>
      <%= hidden_input f, :password, value: @params["password"] %>
      <br>
    <% else %>
      <div class="input">
        <%= label f, :name, "Username" %>
        <%= text_input f, :name %>
      </div>
      <div class="input">
        <%= label f, :password, "Password" %>
        <%= password_input f, :password %>
      </div>
      <%= submit "Log In" %>
    <% end %>
  <% end %>
</div>

<%= hidden_input f, :client_id, value: @client_id %>
<%= hidden_input f, :response_type, value: @response_type %>
<%= hidden_input f, :redirect_uri, value: @redirect_uri %>
<%= hidden_input f, :state, value: @state %>
<% end %>

<%= if Pleroma.Config.oauth_consumer_enabled?() do %>
  <%= render @view_module, Pleroma.Web.Auth.WrapperAuthenticator.oauth_consumer_template(), assigns %>
<% end %>