lib/pleroma/web/router.ex
    post("/statuses/:id/unmute", StatusController, :unmute_conversation)

    post("/push/subscription", SubscriptionController, :create)
    get("/push/subscription", SubscriptionController, :show)
    put("/push/subscription", SubscriptionController, :update)
    delete("/push/subscription", SubscriptionController, :delete)

    get("/suggestions", SuggestionController, :index)
    delete("/suggestions/:account_id", SuggestionController, :dismiss)

    get("/timelines/home", TimelineController, :home)
    get("/timelines/direct", TimelineController, :direct)
    get("/timelines/list/:list_id", TimelineController, :list)
  end

  scope "/api/v1", Pleroma.Web.MastodonAPI do
    pipe_through(:app_api)

    post("/apps", AppController, :create)
    get("/apps/verify_credentials", AppController, :verify_credentials)
  end

  scope "/api/v1", Pleroma.Web.MastodonAPI do
    pipe_through(:api)

    get("/accounts/search", SearchController, :account_search)
    get("/search", SearchController, :search)

    get("/accounts/lookup", AccountController, :lookup)

    get("/accounts/:id/statuses", AccountController, :statuses)
    get("/accounts/:id/followers", AccountController, :followers)
    get("/accounts/:id/following", AccountController, :following)
    get("/accounts/:id", AccountController, :show)

    post("/accounts", AccountController, :create)

    get("/instance", InstanceController, :show)
    get("/instance/peers", InstanceController, :peers)
    get("/instance/rules", InstanceController, :rules)

    get("/statuses", StatusController, :index)
    get("/statuses/:id", StatusController, :show)
    get("/statuses/:id/context", StatusController, :context)
    get("/statuses/:id/card", StatusController, :card)
    get("/statuses/:id/favourited_by", StatusController, :favourited_by)
    get("/statuses/:id/reblogged_by", StatusController, :reblogged_by)

    get("/custom_emojis", CustomEmojiController, :index)

    get("/trends", MastodonAPIController, :empty_array)

    get("/timelines/public", TimelineController, :public)
    get("/timelines/tag/:tag", TimelineController, :hashtag)

    get("/polls/:id", PollController, :show)

    get("/directory", DirectoryController, :index)
  end

  scope "/api/v2", Pleroma.Web.MastodonAPI do
    pipe_through(:api)
    get("/search", SearchController, :search2)

    post("/media", MediaController, :create2)

    get("/suggestions", SuggestionController, :index2)
  end

  scope "/api", Pleroma.Web do
    pipe_through(:config)

    get("/pleroma/frontend_configurations", TwitterAPI.UtilController, :frontend_configurations)
  end

  scope "/api", Pleroma.Web do
    pipe_through(:api)

    get(
      "/account/confirm_email/:user_id/:token",
      TwitterAPI.Controller,
      :confirm_email,
      as: :confirm_email
    )
  end

  scope "/api" do
    pipe_through(:base_api)

    get("/openapi", OpenApiSpex.Plug.RenderSpec, [])
  end

  scope "/api", Pleroma.Web, as: :authenticated_twitter_api do
    pipe_through(:authenticated_api)

    get("/oauth_tokens", TwitterAPI.Controller, :oauth_tokens)
    delete("/oauth_tokens/:id", TwitterAPI.Controller, :revoke_token)
  end

  scope "/", Pleroma.Web do
    # Note: html format is supported only if static FE is enabled
    # Note: http signature is only considered for json requests (no auth for non-json requests)
    pipe_through([:accepts_html_json, :http_signature, :static_fe])

    get("/objects/:uuid", OStatus.OStatusController, :object)
    get("/activities/:uuid", OStatus.OStatusController, :activity)
    get("/notice/:id", OStatus.OStatusController, :notice)

    # Notice compatibility routes for other frontends
    get("/@:nickname/:id", OStatus.OStatusController, :notice)
    get("/@:nickname/posts/:id", OStatus.OStatusController, :notice)
    get("/:nickname/status/:id", OStatus.OStatusController, :notice)

    # Mastodon compatibility routes
    get("/users/:nickname/statuses/:id", OStatus.OStatusController, :object)
    get("/users/:nickname/statuses/:id/activity", OStatus.OStatusController, :activity)
  end

  scope "/", Pleroma.Web do
    # Note: html format is supported only if static FE is enabled
    # Note: http signature is only considered for json requests (no auth for non-json requests)
    pipe_through([:accepts_html_xml_json, :http_signature, :static_fe])

    # Note: returns user _profile_ for json requests, redirects to user _feed_ for non-json ones
    get("/users/:nickname", Feed.UserController, :feed_redirect, as: :user_feed)
  end

  scope "/", Pleroma.Web do
    # Note: html format is supported only if static FE is enabled
    pipe_through([:accepts_html_xml, :static_fe])

    get("/users/:nickname/feed", Feed.UserController, :feed, as: :user_feed)
  end

  scope "/", Pleroma.Web do
    pipe_through(:accepts_html)
    get("/notice/:id/embed_player", OStatus.OStatusController, :notice_player)
  end

  scope "/", Pleroma.Web do
    pipe_through(:accepts_xml_rss_atom)
    get("/tags/:tag", Feed.TagController, :feed, as: :tag_feed)
  end

  scope "/", Pleroma.Web do
    pipe_through(:browser)
    get("/mailer/unsubscribe/:token", Mailer.SubscriptionController, :unsubscribe)
  end

  pipeline :ap_service_actor do
    plug(:accepts, ["activity+json", "json"])
  end

  # Server to Server (S2S) AP interactions
  pipeline :activitypub do
    plug(:ap_service_actor)
    plug(:http_signature)
  end

  # Client to Server (C2S) AP interactions
  pipeline :activitypub_client do
    plug(:ap_service_actor)
    plug(:fetch_session)
    plug(:authenticate)
    plug(:after_auth)
  end

  scope "/", Pleroma.Web.ActivityPub do
    pipe_through([:activitypub_client])

    get("/api/ap/whoami", ActivityPubController, :whoami)
    get("/users/:nickname/inbox", ActivityPubController, :read_inbox)

    get("/users/:nickname/outbox", ActivityPubController, :outbox)
    post("/users/:nickname/outbox", ActivityPubController, :update_outbox)
    post("/api/ap/upload_media", ActivityPubController, :upload_media)

    # The following two are S2S as well, see `ActivityPub.fetch_follow_information_for_user/1`:
    get("/users/:nickname/followers", ActivityPubController, :followers)
    get("/users/:nickname/following", ActivityPubController, :following)
    get("/users/:nickname/collections/featured", ActivityPubController, :pinned)
  end

  scope "/", Pleroma.Web.ActivityPub do
    pipe_through(:activitypub)
    post("/inbox", ActivityPubController, :inbox)
    post("/users/:nickname/inbox", ActivityPubController, :inbox)
  end

  scope "/relay", Pleroma.Web.ActivityPub do
    pipe_through(:ap_service_actor)

    get("/", ActivityPubController, :relay)

    scope [] do
      pipe_through(:http_signature)
      post("/inbox", ActivityPubController, :inbox)
    end

    get("/following", ActivityPubController, :relay_following)
    get("/followers", ActivityPubController, :relay_followers)
  end

  scope "/internal/fetch", Pleroma.Web.ActivityPub do
    pipe_through(:ap_service_actor)

    get("/", ActivityPubController, :internal_fetch)
    post("/inbox", ActivityPubController, :inbox)
  end

  scope "/.well-known", Pleroma.Web do
    pipe_through(:well_known)

    get("/host-meta", WebFinger.WebFingerController, :host_meta)
    get("/webfinger", WebFinger.WebFingerController, :webfinger)
    get("/nodeinfo", Nodeinfo.NodeinfoController, :schemas)
  end

  scope "/nodeinfo", Pleroma.Web do
    get("/:version", Nodeinfo.NodeinfoController, :nodeinfo)
  end

  scope "/", Pleroma.Web do
    pipe_through(:api)

    get("/manifest.json", ManifestController, :show)
  end

  scope "/", Pleroma.Web do
    pipe_through(:pleroma_html)

    post("/auth/password", TwitterAPI.PasswordController, :request)
  end

  scope "/proxy/", Pleroma.Web do
    get("/preview/:sig/:url", MediaProxy.MediaProxyController, :preview)
    get("/preview/:sig/:url/:filename", MediaProxy.MediaProxyController, :preview)
    get("/:sig/:url", MediaProxy.MediaProxyController, :remote)
    get("/:sig/:url/:filename", MediaProxy.MediaProxyController, :remote)
  end

  if Pleroma.Config.get(:env) == :dev do
    scope "/dev" do
      pipe_through([:mailbox_preview])

      forward("/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox")
    end
  end

  scope "/" do
    pipe_through([:pleroma_html, :authenticate, :require_admin])
    live_dashboard("/phoenix/live_dashboard")
  end

  # Test-only routes needed to test action dispatching and plug chain execution
  if Pleroma.Config.get(:env) == :test do
    @test_actions [
      :do_oauth_check,
      :fallback_oauth_check,
      :skip_oauth_check,
      :fallback_oauth_skip_publicity_check,
      :skip_oauth_skip_publicity_check,
      :missing_oauth_check_definition
    ]

    scope "/test/api", Pleroma.Tests do
      pipe_through(:api)

      for action <- @test_actions do
        get("/#{action}", AuthTestController, action)
      end
    end

    scope "/test/authenticated_api", Pleroma.Tests do
      pipe_through(:authenticated_api)

      for action <- @test_actions do
        get("/#{action}", AuthTestController, action)
      end
    end
  end

  scope "/", Pleroma.Web.MongooseIM do
    get("/user_exists", MongooseIMController, :user_exists)
    get("/check_password", MongooseIMController, :check_password)
  end

  scope "/", Pleroma.Web.Fallback do
    get("/registration/:token", RedirectController, :registration_page)
    get("/:maybe_nickname_or_id", RedirectController, :redirector_with_meta)
    match(:*, "/api/pleroma*path", LegacyPleromaApiRerouterPlug, [])
    get("/api*path", RedirectController, :api_not_implemented)
    get("/*path", RedirectController, :redirector_with_preload)

    options("/*path", RedirectController, :empty)
  end

  # TODO: Change to Phoenix.Router.routes/1 for Phoenix 1.6.0+
  def get_api_routes do
    __MODULE__.__routes__()
    |> Enum.reject(fn r -> r.plug == Pleroma.Web.Fallback.RedirectController end)
    |> Enum.map(fn r ->
      r.path

lib/pleroma/web/feed/feed_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.FeedView do
  use Phoenix.HTML
  use Pleroma.Web, :view

  alias Pleroma.Formatter
  alias Pleroma.Object
  alias Pleroma.User
  alias Pleroma.Web.MediaProxy

  require Pleroma.Constants

  @spec pub_date(String.t() | DateTime.t()) :: String.t()
  def pub_date(date) when is_binary(date) do
    date
    |> Timex.parse!("{ISO:Extended}")
    |> pub_date
  end

  def pub_date(%DateTime{} = date), do: Timex.format!(date, "{RFC822}")

  def prepare_activity(activity, opts \\ []) do
    object = Object.normalize(activity, fetch: false)

    actor =
      if opts[:actor] do
        Pleroma.User.get_cached_by_ap_id(activity.actor)
      end

    %{
      activity: activity,
      object: object,
      data: Map.get(object, :data),
      actor: actor
    }
  end

  def most_recent_update(activities) do
    with %{updated_at: updated_at} <- List.first(activities) do
      NaiveDateTime.to_iso8601(updated_at)
    end
  end

  def most_recent_update(activities, user) do
    (List.first(activities) || user).updated_at
    |> NaiveDateTime.to_iso8601()
  end

  def feed_logo do
    case Pleroma.Config.get([:feed, :logo]) do
      nil ->
        "#{Pleroma.Web.Endpoint.url()}/static/logo.svg"

      logo ->
        "#{Pleroma.Web.Endpoint.url()}#{logo}"
    end
    |> MediaProxy.url()
  end

  def logo(user) do
    user
    |> User.avatar_url()
    |> MediaProxy.url()
  end

  def last_activity(activities), do: List.last(activities)

  def activity_title(%{"content" => content}, opts \\ %{}) do
    content
    |> Pleroma.Web.Metadata.Utils.scrub_html()
    |> Pleroma.Emoji.Formatter.demojify()
    |> Formatter.truncate(opts[:max_length], opts[:omission])
    |> escape()
  end

  def activity_content(%{"content" => content}) do
    content
    |> String.replace(~r/[\n\r]/, "")
    |> escape()
  end

  def activity_content(_), do: ""

  def activity_context(activity), do: escape(activity.data["context"])

  def attachment_href(attachment) do
    attachment["url"]
    |> hd()
    |> Map.get("href")
  end

  def attachment_type(attachment) do
    attachment["url"]
    |> hd()
    |> Map.get("mediaType")
  end

  def get_href(id) do
    with %Object{data: %{"external_url" => external_url}} <- Object.get_cached_by_ap_id(id) do
      external_url
    else
      _e -> id
    end
  end

  def escape(html) do
    html
    |> html_escape()
    |> safe_to_string()
  end
end

lib/pleroma/web/feed/tag_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.TagController do
  use Pleroma.Web, :controller

  alias Pleroma.Config
  alias Pleroma.Web.ActivityPub.ActivityPub
  alias Pleroma.Web.Feed.FeedView

  def feed(conn, params) do
    if Config.get!([:instance, :public]) do
      render_feed(conn, params)
    else
      render_error(conn, :not_found, "Not found")
    end
  end

  defp render_feed(conn, %{"tag" => raw_tag} = params) do
    {format, tag} = parse_tag(raw_tag)

    activities =
      %{type: ["Create"], tag: tag}
      |> Pleroma.Maps.put_if_present(:max_id, params["max_id"])
      |> ActivityPub.fetch_public_activities()

    conn
    |> put_resp_content_type("application/#{format}+xml")
    |> put_view(FeedView)
    |> render("tag.#{format}",
      activities: activities,
      tag: tag,
      feed_config: Config.get([:feed])
    )
  end

  @spec parse_tag(binary() | any()) :: {format :: String.t(), tag :: String.t()}
  defp parse_tag(raw_tag) do
    case is_binary(raw_tag) && Enum.reverse(String.split(raw_tag, ".")) do
      [format | tag] when format in ["rss", "atom"] ->
        {format, Enum.join(tag, ".")}

      _ ->
        {"atom", raw_tag}
    end
  end
end

lib/pleroma/web/feed/user_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2021 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.UserController do
  use Pleroma.Web, :controller

  alias Pleroma.Config
  alias Pleroma.User
  alias Pleroma.Web.ActivityPub.ActivityPub
  alias Pleroma.Web.ActivityPub.ActivityPubController
  alias Pleroma.Web.Feed.FeedView

  plug(Pleroma.Web.Plugs.SetFormatPlug when action in [:feed_redirect])

  action_fallback(:errors)

  def feed_redirect(%{assigns: %{format: "html"}} = conn, %{"nickname" => nickname}) do
    with {_, %User{} = user} <- {:fetch_user, User.get_cached_by_nickname_or_id(nickname)} do
      Pleroma.Web.Fallback.RedirectController.redirector_with_meta(conn, %{user: user})
    else
      _ -> Pleroma.Web.Fallback.RedirectController.redirector(conn, nil)
    end
  end

  def feed_redirect(%{assigns: %{format: format}} = conn, _params)
      when format in ["json", "activity+json"] do
    ActivityPubController.call(conn, :user)
  end

  def feed_redirect(conn, %{"nickname" => nickname}) do
    with {_, %User{} = user} <- {:fetch_user, User.get_cached_by_nickname(nickname)} do
      redirect(conn, external: "#{Routes.user_feed_url(conn, :feed, user.nickname)}.atom")
    end
  end

  def feed(conn, %{"nickname" => nickname} = params) do
    format = get_format(conn)

    format =
      if format in ["atom", "rss"] do
        format
      else
        "atom"
      end

    with {_, %User{local: true} = user} <- {:fetch_user, User.get_cached_by_nickname(nickname)},
         {_, :visible} <- {:visibility, User.visible_for(user, _reading_user = nil)} do
      activities =
        %{
          type: ["Create"],
          actor_id: user.ap_id
        }
        |> Pleroma.Maps.put_if_present(:max_id, params["max_id"])
        |> ActivityPub.fetch_public_or_unlisted_activities()

      conn
      |> put_resp_content_type("application/#{format}+xml")
      |> put_view(FeedView)
      |> render("user.#{format}",
        user: user,
        activities: activities,
        feed_config: Config.get([:feed])
      )
    end
  end

  def errors(conn, {:error, :not_found}) do
    render_error(conn, :not_found, "Not found")
  end

  def errors(conn, {:fetch_user, %User{local: false}}), do: errors(conn, {:error, :not_found})
  def errors(conn, {:fetch_user, nil}), do: errors(conn, {:error, :not_found})

  def errors(conn, {:visibility, _}), do: errors(conn, {:error, :not_found})

  def errors(conn, _) do
    render_error(conn, :internal_server_error, "Something went wrong")
  end
end

lib/pleroma/web/templates/feed/feed/_activity.atom.eex
<entry>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <id><%= @data["id"] %></id>
  <title><%= activity_title(@data, Keyword.get(@feed_config, :post_title, %{})) %></title>
  <content type="html"><%= activity_content(@data) %></content>
  <published><%= @activity.data["published"] %></published>
  <updated><%= @activity.data["published"] %></updated>
  <ostatus:conversation ref="<%= activity_context(@activity) %>">
    <%= activity_context(@activity) %>
  </ostatus:conversation>
  <link href="<%= activity_context(@activity) %>" rel="ostatus:conversation"/>

  <%= if @data["summary"] do %>
    <summary><%= escape(@data["summary"]) %></summary>
  <% end %>

  <%= if @activity.local do %>
    <link type="application/atom+xml" href='<%= @data["id"] %>' rel="self"/>
    <link type="text/html" href='<%= @data["id"] %>' rel="alternate"/>
  <% else %>
    <link type="text/html" href='<%= @data["external_url"] %>' rel="alternate"/>
  <% end %>

  <%= for tag <- Pleroma.Object.hashtags(@object) do %>
    <category term="<%= tag %>"></category>
  <% end %>

  <%= for attachment <- @data["attachment"] || [] do %>
    <link rel="enclosure" href="<%= attachment_href(attachment) %>" type="<%= attachment_type(attachment) %>"/>
  <% end %>

  <%= if @data["inReplyTo"] do %>
    <thr:in-reply-to ref='<%= @data["inReplyTo"] %>' href='<%= get_href(@data["inReplyTo"]) %>'/>
  <% end %>

  <%= for id <- @activity.recipients do %>
    <%= if id == Pleroma.Constants.as_public() do %>
      <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
    <% else %>
      <%= unless Regex.match?(~r/^#{Pleroma.Web.Endpoint.url()}.+followers$/, id) do %>
        <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="<%= id %>"/>
      <% end %>
    <% end %>
  <% end %>

  <%= for {emoji, file} <- @data["emoji"] || %{} do %>
    <link name="<%= emoji %>" rel="emoji" href="<%= file %>"/>
  <% end %>
</entry>

lib/pleroma/web/templates/feed/feed/_activity.rss.eex
<item>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <guid><%= @data["id"] %></guid>
  <title><%= activity_title(@data, Keyword.get(@feed_config, :post_title, %{})) %></title>
  <description><%= activity_content(@data) %></description>
  <pubDate><%= @activity.data["published"] %></pubDate>
  <updated><%= @activity.data["published"] %></updated>
  <ostatus:conversation ref="<%= activity_context(@activity) %>">
    <%= activity_context(@activity) %>
  </ostatus:conversation>

  <%= if @data["summary"] do %>
    <description><%= escape(@data["summary"]) %></description>
  <% end %>

  <%= if @activity.local do %>
    <link><%= @data["id"] %></link>
  <% else %>
    <link><%= @data["external_url"] %></link>
  <% end %>

  <link rel="ostatus:conversation"><%= activity_context(@activity) %></link>

  <%= for tag <- Pleroma.Object.hashtags(@object) do %>
    <category term="<%= tag %>"></category>
  <% end %>

  <%= for attachment <- @data["attachment"] || [] do %>
    <link type="<%= attachment_type(attachment) %>"><%= attachment_href(attachment) %></link>
  <% end %>

  <%= if @data["inReplyTo"] do %>
    <thr:in-reply-to ref='<%= @data["inReplyTo"] %>' href='<%= get_href(@data["inReplyTo"]) %>'/>
  <% end %>

  <%= for id <- @activity.recipients do %>
    <%= if id == Pleroma.Constants.as_public() do %>
      <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection">http://activityschema.org/collection/public</link>
    <% else %>
      <%= unless Regex.match?(~r/^#{Pleroma.Web.Endpoint.url()}.+followers$/, id) do %>
        <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person"><%= id %></link>
      <% end %>
    <% end %>
  <% end %>

  <%= for {emoji, file} <- @data["emoji"] || %{} do %>
    <link name="<%= emoji %>" rel="emoji"><%= file %></link>
  <% end %>
</item>

lib/pleroma/web/templates/feed/feed/_author.atom.eex
<author>
  <id><%= @user.ap_id %></id>
  <activity:object>http://activitystrea.ms/schema/1.0/person</activity:object>
  <uri><%= @user.ap_id %></uri>
  <poco:preferredUsername><%= @user.nickname %></poco:preferredUsername>
  <poco:displayName><%= @user.name %></poco:displayName>
  <poco:note><%= escape(@user.bio) %></poco:note>
  <summary><%= escape(@user.bio) %></summary>
  <name><%= @user.nickname %></name>
  <link rel="avatar" href="<%= User.avatar_url(@user) %>"/>
  <%= if User.banner_url(@user) do %>
    <link rel="header" href="<%= User.banner_url(@user) %>"/>
  <% end %>
  <%= if @user.local do %>
    <ap_enabled>true</ap_enabled>
  <% end %>
</author>

lib/pleroma/web/templates/feed/feed/_author.rss.eex
<managingEditor>
  <guid><%= @user.ap_id %></guid>
  <activity:object>http://activitystrea.ms/schema/1.0/person</activity:object>
  <uri><%= @user.ap_id %></uri>
  <poco:preferredUsername><%= @user.nickname %></poco:preferredUsername>
  <poco:displayName><%= @user.name %></poco:displayName>
  <poco:note><%= escape(@user.bio) %></poco:note>
  <description><%= escape(@user.bio) %></description>
  <name><%= @user.nickname %></name>
  <link rel="avatar"><%= User.avatar_url(@user) %></link>
  <%= if User.banner_url(@user) do %>
    <link rel="header"><%= User.banner_url(@user) %></link>
  <% end %>
  <%= if @user.local do %>
    <ap_enabled>true</ap_enabled>
  <% end %>
</managingEditor>

lib/pleroma/web/templates/feed/feed/_tag_activity.xml.eex
<item>
  <title><%= activity_title(@data, Keyword.get(@feed_config, :post_title, %{})) %></title>


  <guid isPermalink="true"><%= activity_context(@activity) %></guid>
  <link><%= activity_context(@activity) %></link>
  <pubDate><%= pub_date(@activity.data["published"]) %></pubDate>

  <description><%= activity_content(@data) %></description>
  <%= for attachment <- @data["attachment"] || [] do %>
    <enclosure url="<%= attachment_href(attachment) %>" type="<%= attachment_type(attachment) %>"/>
  <% end %>

</item>

lib/pleroma/web/templates/feed/feed/_tag_author.atom.eex
<author>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <id><%= @actor.ap_id %></id>
    <uri><%= @actor.ap_id %></uri>
    <name><%= @actor.nickname %></name>
    <summary><%= escape(@actor.bio) %></summary>
    <link rel="avatar" href="<%= User.avatar_url(@actor) %>"/>
    <%= if User.banner_url(@actor) do %>
      <link rel="header" href="<%= User.banner_url(@actor) %>"/>
    <% end %>
    <%= if @actor.local do %>
      <ap_enabled>true</ap_enabled>
    <% end %>
  
    <poco:preferredUsername><%= @actor.nickname %></poco:preferredUsername>        
    <poco:displayName><%= @actor.name %></poco:displayName>
    <poco:note><%= escape(@actor.bio) %></poco:note>    
</author>

lib/pleroma/web/templates/feed/feed/tag.atom.eex
<?xml version="1.0" encoding="UTF-8"?>

<feed xml:lang="en-US" xmlns="http://www.w3.org/2005/Atom"
      xmlns:thr="http://purl.org/syndication/thread/1.0"
      xmlns:georss="http://www.georss.org/georss"
      xmlns:activity="http://activitystrea.ms/spec/1.0/"
      xmlns:media="http://purl.org/syndication/atommedia"
      xmlns:poco="http://portablecontacts.net/spec/1.0"
      xmlns:ostatus="http://ostatus.org/schema/1.0"
      xmlns:statusnet="http://status.net/schema/api/1/">

    <id><%= '#{Routes.tag_feed_url(@conn, :feed, @tag)}.rss' %></id>
    <title>#<%= @tag %></title>

    <subtitle>These are public toots tagged with #<%= @tag %>. You can interact with them if you have an account anywhere in the fediverse.</subtitle>
    <logo><%= feed_logo() %></logo>
    <updated><%= most_recent_update(@activities) %></updated>
    <link rel="self" href="<%= '#{Routes.tag_feed_url(@conn, :feed, @tag)}.atom'  %>" type="application/atom+xml"/>
    <%= for activity <- @activities do %>
    <%= render @view_module, "_tag_activity.atom", Map.merge(assigns, prepare_activity(activity, actor: true)) %>
    <% end %>
</feed>

lib/pleroma/web/templates/feed/feed/tag.rss.eex
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:webfeeds="http://webfeeds.org/rss/1.0">
  <channel>


    <title>#<%= @tag %></title>
    <description>These are public toots tagged with #<%= @tag %>. You can interact with them if you have an account anywhere in the fediverse.</description>
    <link><%= '#{Routes.tag_feed_url(@conn, :feed, @tag)}.rss' %></link>
    <webfeeds:logo><%= feed_logo() %></webfeeds:logo>
    <webfeeds:accentColor>2b90d9</webfeeds:accentColor>
    <%= for activity <- @activities do %>
    <%= render @view_module, "_tag_activity.xml", Map.merge(assigns, prepare_activity(activity)) %>
    <% end %>
  </channel>
</rss>